### ISSUE TITLE
Addon broke the shift+click in chat

### ISSUE THREAD

**Issue by DenisKn** [christophrus/CensusPlusClassic#18]
Addon broke the **shift+click** in the chat (Nothing happens when **shift+click** on a username). 
Everything works if I disable the addon.

**Comment by Siothie** [comment]
I think because SendWho() was made protected the Addon wont work anymore until a workaround is found.
So just disable it for now to use the shift click function again.
Btw it also "broke" it while it was working, simply because the addon was who'ing a lot of people and shift click does the same wrapped in a different skin. Thats why the shift+click answers came in delayed.
At least thats my guess without having looked at the proper code
