### ISSUE TITLE
Not Scanning

### ISSUE THREAD

**Issue by ISJ-439** [christophrus/CensusPlusClassic#21]
All add-ons disabled but this one, on a fresh level 1 char. Any ideas? 

I clicked "Stop" > "Purge" > "Take", still nothing.

![image](https://user-images.githubusercontent.com/10002986/66061696-2f201000-e4fd-11e9-80a2-2d95c8ea0a82.png)

**Comment by ISJ-439** [comment]
Settings: 
![image](https://user-images.githubusercontent.com/10002986/66061834-71495180-e4fd-11e9-87ae-863439800da9.png)

**Comment by ISJ-439** [comment]
Seems to work if I click "ManualWho"
![image](https://user-images.githubusercontent.com/10002986/66062868-73acab00-e4ff-11e9-981d-11c09d6503aa.png)

**Comment by ISJ-439** [comment]
Then if left alone it tried the same query over and over.
![image](https://user-images.githubusercontent.com/10002986/66062912-8de68900-e4ff-11e9-9abf-d0b9c8610b1b.png)

**Comment by saxainden** [comment]
I also am having this problem.  Wiped all CensusPlusClassic.lua and .bak files, deleted addons and reinstalled 0.7.0.  Also tried 0.6.0 and appeared to have the same problem.

**Comment by saxainden** [comment]
Ah. appears that Blizzard broke the SendWho() function so this is probably why this is failing..

**Comment by ISJ-439** [comment]
Can we make it so there's a macro-able manual method so I can bind it to a action?

**Comment by flaw** [comment]
You can already do "/run ManualWho()" in a macro and it'll trigger the CensusPlus manual who function.
I've made a macro which runs ManualWho() whenever I mount up, it seems to take around an hour to get a full census but it does work without me having to do much extra.

To clarify for others stumbling onto this: the automatic census does not work after Blizzard made it so that it's not possible for addons to automatically call the Who methods. It now requires an explicit user action to trigger a who request, which is why you now need to do "/run ManualWho()" either in a dedicated macro or as part of some other macro in order to keep the census scan going.
