### ISSUE TITLE
Error when mouse clicks in interface is selected

### ISSUE THREAD

**Issue by RedDrumJay** [christophrus/CensusPlusClassic#28]
No issue with world 3D option, but when both are clicked it throws this error:

Date: 2019-11-25 21:36:55
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\CensusPlusClassic\CensusPlusClassic.lua line 532:
   attempt to call method 'HookScript' (a string value)
Debug:
   ...rface\AddOns\CensusPlusClassic\CensusPlusClassic.lua:532: InitializeExperimental()
   ...rface\AddOns\CensusPlusClassic\CensusPlusClassic.lua:1688:
      ...rface\AddOns\CensusPlusClassic\CensusPlusClassic.lua:1658
Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GRM_AuditToolText5 = GRM_AuditToolText5 {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 Recount_MainWindow_Bar6 = Recount_MainWindow_Bar6 {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 741
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem2AltCurrencyFrameItem1Text = MerchantItem2AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:602
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2373
 ZygorGuidesViewerFrame_Step6_Line20ContentText = ZygorGuidesViewerFrame_Step6_Line20ContentText {
 }
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use Colossus Smash.

Colossus Smash increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 951
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 PallyPowerBlessingsFramePlayer10Line5 = PallyPowerBlessingsFramePlayer10Line5 {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 nUI_TopRightBar_Button1Icon = nUI_TopRightBar_Button1Icon {
 }
 GRM_BirthdayTooltipStatusBar = GRM_BirthdayTooltipStatusBar {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee ability with an increased range that consumes Combo Points."
 ZygorGuidesViewerFrame_Act1_17PetActionShine15 = ZygorGuidesViewerFrame_Act1_17PetActionShine15 {
 }
 StanceButton4FlyoutArrow = StanceButton4FlyoutArrow {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 ZygorGuidesViewerFrame_Border_Flash_flash_flashOut = ZygorGuidesViewerFrame_Border_Flash_flash_flashOut {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @Interface\FrameXML\ChatFrame.lua:1111
 SLASH_STOPATTACK1 = "/stopattack"
 SpyStatsPlayerHistoryFrameListFrameLine10Level = SpyStatsPlayerHistoryFrameListFrameLine10Level {
 }
 GRM_ExportSelectedRangeButton = GRM_ExportSelectedRangeButton {
 }
 SortQuestWatches = <function> defined =[C]:-1
 C
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  WowheadLooter, v11302
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CensusPlusClassic, v1.13.2
  CharacterStatsClassic, v2.6.1
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GTFO, v4.51
  GuildRosterManager, v1.831
  Informant, v8.2.6508 (SwimmingSeadragon)
  nUI, v1.13.2.31727.3
  PallyPower, vv1.1a-classic 
  Prat30, v3.7.36
  Prat30Libraries, v
  Questie, v5.2.3
  Recount, vv8.2.5b
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.15
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomTom, vv80205-1.0.8
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=534)

**Comment by b-morgan** [comment]
Same issue here.

1x ...rfaceCensusPlusClassic\CensusPlusClassic-1.13.2.lua:532: attempt to call method 'HookScript' (a string value)
...rfaceCensusPlusClassic\CensusPlusClassic-1.13.2.lua:532: in function `InitializeExperimental'
...rfaceCensusPlusClassic\CensusPlusClassic-1.13.2.lua:1688: in function <...rfaceCensusPlusClassic\CensusPlusClassic.lua:1658>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 BaseAPIMixin = <table> {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 TrinketMenu_Menu8HotKey = TrinketMenu_Menu8HotKey {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 741
 TrinketMenu_Menu4FlyoutArrow = TrinketMenu_Menu4FlyoutArrow {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 ArmoryQuestLogRequiredMoneyFrameGoldButtonText = ArmoryQuestLogRequiredMoneyFrameGoldButtonText {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 Wardrobe_IconPickerFrame_IconFrame_2_6_Texture = Wardrobe_IconPickerFrame_IconFrame_2_6_Texture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem2AltCurrencyFrameItem1Text = MerchantItem2AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 ArmorySpellButton5 = ArmorySpellButton5 {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:602
 MANA = "Mana"
 ArmoryMainHandSlot = ArmoryMainHandSlot {
 }
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML\FloatingChatFrame.lua:2373
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 951
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 SLASH_LibQTip1 = "/qtip"
 ArmoryFrameBottomBorder = ArmoryFrameBottomBorder {
 }
 TrinketMenu_Trinket1Shine13 = TrinketMenu_Trinket1Shine13 {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 AccountantClassicFrameTab1RightDisabled = AccountantClassicFrameTab1RightDisabled {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee ability with an increased range that consumes Combo Points."
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 ArmoryTradeSkillFilterDropDownLeft = ArmoryTradeSkillFilterDropDownLeft {
 }
 StanceButton4FlyoutArrow = StanceButton4FlyoutArrow {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 ArmoryTalentFrameBranch2 = ArmoryTalentFrameBranch2 {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML\ChatFrame.lua:1111
 SLASH_STOPATTACK1

**Comment by christophrus** [comment]
I have removed that feature from the addon with 0.8.3, because there were a lot of people that had trouble with it in combination with some addons and I was unable to debug it because I never got the error message, even if I installed the exact same addons like you had.
