### ISSUE TITLE
Web for collecting data (wowclassicpopulation.com) is not working

### ISSUE THREAD

**Issue by benesva4** [christophrus/CensusPlusClassic#8]
Website just tells me:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by furydeath9** [comment]
Well since they just copy and make the retail WoW Census work with classic ( without even asking it seems) Maybe the web site isn't even up yet. From what I can real tho the REAL Census add on will no be doing anything with classic at this time it seems.

**Comment by b-morgan** [comment]
I'm happy to collect data but if there's no site to contribute to then I might as well delete the addon.

**Comment by mroswald** [comment]
I tried to bring something up quickly: https://wowpop.appspot.com/

I don't want to steal anybody's idea. This is just meant as interim solution.

cc @b-morgan

**Comment by Hoaas** [comment]
@mroswald Looking forward to graphs :D

**Comment by b-morgan** [comment]
I tried to upload my data but got the error: "File can not exeed 2MB"

I would have rather not gotten an error message but the spelling error in the error message is not mine. 

Here's my data in case you need it for debugging.
[CensusPlusClassic.zip](https://github.com/christophrus/CensusPlusClassic/files/3575983/CensusPlusClassic.zip)

**Comment by mroswald** [comment]
Thanks, intentionally capped but can increase the limit

**Comment by ChangeUsername** [comment]
Nice work @mroswald - I also wanted to host a stable site but it seems like you were first :) 
Can we get some kind of info how many rough uploads (in 100s) or latest uploads you got for each realm?

**Comment by mroswald** [comment]
@ChangeUsername I was planning to open the code base for more developers - don't worry. I just wanted to prepare it a bit (not code cleanup, but help for setting up locally with database seeds etc.). I would like to include more information about the data, which needs another round of parsing through each file. I only can say at this point that it's 100-300 files each day overall (wild guess).

Are you into PHP/Laravel and interested?

**Comment by gamer4eg** [comment]
> I tried to bring something up quickly: https://wowpop.appspot.com/
> 
> I don't want to steal anybody's idea. This is just meant as interim solution.
> 
> cc @b-morgan

add ruRU realm plz. thx!

**Comment by Hoaas** [comment]
Would be happy to try to improve the page if the code is made public. (not a PHP pro though :()

**Comment by mroswald** [comment]
@gamer4eg Is on the way right now! Implemented the localised importer this morning

**Comment by mroswald** [comment]
@Hoaas I'm not sure if I want to open-source the project, would like to invite a few people first and organise further from that :) Also happy to have someone on the team who is more into organisation and takes care about the project itself!

**Comment by gamer4eg** [comment]
> @gamer4eg Is on the way right now! Implemented the localised importer this morning

thx!

**Comment by vahlback** [comment]
@mroswald would be awesome to have the functionality to make queries with some specified parameters on the site. For example i don't think level>5 cuttoff is high enough, i'd want to query [myserver][level>10] or something like that.

**Comment by Hoaas** [comment]
Also filtering on one graph should affect other grahps. Want to see how many warriors are superior gnomes. #featurerequest

**Comment by christophrus** [comment]
Website is up and runnig again. Would be nice, if you upload your data for at least historical purpose.

**Comment by Taemojitsu** [comment]
> I tried to bring something up quickly: https://wowpop.appspot.com/

It would be a lot more useful if you did fancy statistics that matched the data points to the smooth daily activity graph that used to be available from http://www.warcraftrealms.com/activity.php

Compare the current spiky, noisy graph shown there with the very smooth one at
https://web.archive.org/web/20060328013154/http://www.warcraftrealms.com/activity.php

This is much more useful with a low number of data points than trying to count all the characters on a realm. The hard part statistically is probably to determine the peak activity point, if it differs from that predicted by server time, and determine whether the daily activity graph differs materially from the average one in other ways. For example, people from more diverse time zones playing will flatten it. (Maybe if Oceanic people play on US Roleplaying servers.) Weekly activity probably also shows a cyclic trend, and accounting for that in the prediction would further improve accuracy.

If doing all this statistical stuff, maybe instead of showing total number of characters, you could predict peak population, or peak and minimum daily population (averaged for all days of the week, maybe).
